config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/confirmed'
  get 'home/recovered'
  get 'home/deaths'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_global_summary_service  
  def index
  @summary = @summary_service.general
  end

  def confirmed
    @confirmed = @summary_service.confirmed
  end

  def recovered
    @recovered = @summary_service.recovered
  end

  def deaths
    @deaths = @summary_service.deaths
  end

  private 
  
  def set_global_summary_service
    @summary_service = GlobalSummary.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/confirmed.html.erb
<h1 text align="center">Casos confirmados</h1>

<table text align="center">
     <thead>
        <td>Estado</td>
        <td>Confirmados</td>
        <td>Última atualização</td>
    </thead>
    <tbody>
        <% @confirmed.each do |confirmed| %>
            <tr>
            <td><%= confirmed['provinceState']%></td>
            <td><%= confirmed['confirmed']%></td>
            <td><%= Time.at(confirmed['lastUpdate'].to_i/1000).strftime('%d/%m/%Y %H:%M:%S')%></td>
            </tr>
        <% end %>

    </tbody>
</table>

app/views/home/deaths.html.erb
<h1 text align="center">Mortes por Covid</h1>

<table text align="center">
    <thead>
        <td>Estado</td>
        <td>Mortes</td>
        <td>Última atualização</td> 
    </thead>
    <tbody>
        <% @deaths.each do |deaths| %>
         <tr>
           <td><%= deaths ['provinceState']%></td>
           <td><%= deaths ['deaths']%></td>
           <td><%= Time.at(deaths ['lastUpdate'].to_i/1000).strftime('%d/%m/%Y %H:%M:%S')%></td>
         </tr>
         <% end %>   
     </tbody>
</table>

app/views/home/index.html.erb
<h1 text align="center">Dados atualizados Covid19 no Brasil</h1>
<table>
<h2>Filtros</h2>
<li><%= link_to "Confirmados (Por estado)", home_confirmed_path%></li>
<li><%= link_to "Recuperados (Por estado)", home_recovered_path%></li>
<li><%= link_to "Mortes (Por estado)", home_deaths_path%></li>
</table>
<p text align="center">Confirmados: <%=@summary ['confirmed']['value']%></p>
<p text align="center">Recuperados: <%=@summary ['recovered']['value']%></p>
<p text align="center">Mortes: <%=@summary ['deaths']['value']%></p>

app/views/home/recovered.html.erb
<h1 text align="center">Recuperados</h1>

<table text align="center">
    <thead>
        <td>Estado</td>
        <td>Recuperados</td>
        <td>Última atualização</td>
    </thead>
    <tbody>

        <% @recovered.each do |recovered| %>
            <tr>
            <td><%= recovered ['provinceState']%></td>   
            <td><%= recovered ['recovered']%></td>
            <td><%= Time.at(recovered ['lastUpdate'].to_i/1000).strftime('%d/%m/%Y %H:%M:%S')%></td>
            </tr>
            <% end %>
     </tbody>

</table>